package com.kitchenkeeper.android;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Matrix;
import android.media.ExifInterface;
import android.net.Uri;
import android.util.Base64;
import org.json.JSONObject;
import org.json.JSONArray;
import java.io.*;
import java.util.*;
final class Photos {
    private final Context context; private final File directory;
    Photos(Context c){context=c;directory=new File(c.getFilesDir(),"photos");if(!directory.exists())directory.mkdirs();}
    File file(String id){if(!id.matches("[a-fA-F0-9-]{36}"))return null;return new File(directory,id+".jpg");}
    boolean exists(String id){File f=file(id);return f!=null&&f.isFile();}
    static byte[] read(InputStream in,int maximum)throws IOException{if(in==null)throw new IOException("File unavailable.");try(InputStream source=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int count;while((count=source.read(buffer))!=-1){if(out.size()+count>maximum)throw new IOException("This file is too large.");out.write(buffer,0,count);}return out.toByteArray();}}
    String add(Uri uri)throws Exception{byte[] bytes=read(context.getContentResolver().openInputStream(uri),25000000);BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(options.outWidth<1||options.outHeight<1)throw new IOException("Choose a readable photo.");options.inSampleSize=1;while(Math.max(options.outWidth,options.outHeight)/options.inSampleSize>2000)options.inSampleSize*=2;options.inJustDecodeBounds=false;Bitmap original=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(original==null)throw new IOException("Choose a different photo.");Bitmap output=original;try{ExifInterface exif=new ExifInterface(new ByteArrayInputStream(bytes));Matrix transform=new Matrix();switch(exif.getAttributeInt(ExifInterface.TAG_ORIENTATION,ExifInterface.ORIENTATION_NORMAL)){case ExifInterface.ORIENTATION_ROTATE_90:transform.postRotate(90);break;case ExifInterface.ORIENTATION_ROTATE_180:transform.postRotate(180);break;case ExifInterface.ORIENTATION_ROTATE_270:transform.postRotate(270);break;case ExifInterface.ORIENTATION_FLIP_HORIZONTAL:transform.setScale(-1,1);break;case ExifInterface.ORIENTATION_FLIP_VERTICAL:transform.setScale(1,-1);break;case ExifInterface.ORIENTATION_TRANSPOSE:transform.setScale(-1,1);transform.postRotate(90);break;case ExifInterface.ORIENTATION_TRANSVERSE:transform.setScale(-1,1);transform.postRotate(270);break;default:break;}if(!transform.isIdentity())output=Bitmap.createBitmap(original,0,0,original.getWidth(),original.getHeight(),transform,true);}catch(IOException ignored){}
      String id=KitchenStore.id();try(FileOutputStream stream=new FileOutputStream(file(id))){if(!output.compress(Bitmap.CompressFormat.JPEG,86,stream))throw new IOException("Could not save this photo.");}finally{if(output!=original)output.recycle();original.recycle();}return id;}
    String dataUrl(String id)throws Exception{File f=file(id);if(f==null||!f.exists())throw new IOException("Choose a label photo first.");return "data:image/jpeg;base64,"+Base64.encodeToString(read(new FileInputStream(f),4000000),Base64.NO_WRAP);}
    JSONObject export(JSONObject backup)throws Exception{JSONObject images=new JSONObject();Set<String> used=new HashSet<>();for(String type:new String[]{"items","recipes"}){JSONArray list=backup.optJSONArray(type);if(list!=null)for(int i=0;i<list.length();i++)used.add(list.getJSONObject(i).optString("photo"));}long total=0;for(String id:used)if(exists(id)){byte[] bytes=read(new FileInputStream(file(id)),4000000);total+=bytes.length;if(total>35000000)throw new IOException("Photos exceed the 35 MB backup limit. Export records only, or reduce your photo sizes.");KitchenStore.put(images,id,Base64.encodeToString(bytes,Base64.NO_WRAP));}KitchenStore.put(backup,"photos",images);return backup;}
    Set<String> present(){Set<String> ids=new HashSet<>();File[] files=directory.listFiles();if(files!=null)for(File f:files)if(f.getName().endsWith(".jpg"))ids.add(f.getName().substring(0,f.getName().length()-4));return ids;}
    Set<String> importPhotos(JSONObject backup)throws Exception{Set<String> created=new HashSet<>();JSONObject p=backup.optJSONObject("photos");if(p==null)return created;try{if(p.length()>500)throw new IOException("Too many photos in this backup.");long total=0;for(Iterator<String> it=p.keys();it.hasNext();){String id=it.next();File target=file(id);if(target==null)throw new IOException("Invalid photo identifier in backup.");if(target.exists())continue;byte[] bytes=Base64.decode(p.getString(id),Base64.DEFAULT);total+=bytes.length;if(bytes.length>4000000||total>35000000)throw new IOException("Backup photos exceed the import limit.");BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(options.outWidth<=0||options.outHeight<=0||options.outWidth>6000||options.outHeight>6000)throw new IOException("Invalid photo in backup.");try(FileOutputStream out=new FileOutputStream(target)){out.write(bytes);}created.add(id);}return created;}catch(Exception e){remove(created);throw e;}}
    void remove(Set<String> ids){for(String id:ids){File f=file(id);if(f!=null)f.delete();}}
}
